APPLY_FIXES: none
FILTER_REGEX_INCLUDE: (.editorconfig|.github/|edge-agent-sdk/src/|sampleapp/src/|protosLib/src/)
FILTER_REGEX_EXCLUDE: (tests/)
VALIDATE_ALL_CODEBASE: false

ENABLE_LINTERS:
  - KOTLIN_KTLINT
  - GHERKIN_GHERKIN_LINT
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWNLINT

