APPLY_FIXES: none
FILTER_REGEX_INCLUDE: (.editorconfig|.github/|atala-prism-sdk/src/|sampleapp/src/|protosLib/src/)
VALIDATE_ALL_CODEBASE: false

ENABLE_LINTERS:
  - KOTLIN_KTLINT
  - GHERKIN_GHERKIN_LINT
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWNLINT

KOTLIN_KTLINT_CLI_LINT_MODE: project
