---
name: Build and Test

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: 11
  NODEJS_VERSION: 16.17.0
  ATALA_GITHUB_ACTOR: ${{ secrets.ATALA_GITHUB_ACTOR }}
  ATALA_GITHUB_TOKEN: ${{ secrets.ATALA_GITHUB_TOKEN }}

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "zulu"

      - name: Build for JS, Android, JVM
        run: |
          ./gradlew build test koverXmlReport koverHtmlReport

      - name: Coverage Report
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/atala-prism-sdk/build/reports/kover/report.xml
          token: ${{ env.ATALA_GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "${{ github.workspace }}/atala-prism-sdk/build/test-results/testReleaseUnitTest/TEST-*.xml"
          comment_title: "Unit Test Results"
          check_name: "Unit Test Results"

      - name: Publish coverage report
        uses: actions/upload-artifact@v3
        with:
          name: kover-html
          path: atala-prism-sdk/build/kover/atala-prism-sdk/xml
          if-no-files-found: error
